language: python

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - python setup.py install
  - pip install -r requirements.txt
script: pytest # run tests
