language: python
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install ".[test]" . # install package + test dependencies
script: pytest # run tests
